on: workflow_dispatch

name: Aikido Scan Dockerized
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: aikidosecurity/local-scanner:latest
    steps: 
      - uses: actions/checkout@v4 
        with: 
          token: ${{ secrets.GITHUB_TOKEN }} 
          path: demo-app
      - name: Run scan
        run: aikido-local-scanner scan demo-app --apikey AIK_CI_xHvwurJxXp3vGkAjAqOuxiY4abSuxISH7cujGLa6mnVVAarh8ACmq8nNyk3xe0s7 --repositoryname MyRepo --branchname master --fail-on critical
