on: workflow_dispatch

name: Aikido Image Scan Dockerized
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: sanderkeymeulen/aikidoselfscannerdocker
    steps: 
      - uses: actions/checkout@v4 
        with: 
          token: ${{ secrets.GITHUB_TOKEN }} 
          path: demo-app
      - name: Run scan
        run: aikido-local-scanner image-scan demo-app/image.tar --apikey AIK_CI_SCdrHwC8Ls64drKGrUYf0Njtu7hCDBkbX5VH8yIHVt0L3eozVVTyrl2FqKwdsTai
