on: workflow_dispatch

name: Scan
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Aikido selfscanner
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'AikidoSec/aikido-selfscanner'
          version: 'tags/v39f3d0caf5cc61ee318dde72494950209a1834df'
          file: 'aikidoselfscanner_linux_X86_64_v39f3d0caf5cc61ee318dde72494950209a1834df.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
