on: workflow_dispatch

name: Scan
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Aikido selfscanner
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'skeymeulen/releasetetest'
          version: 'tags/v1'
          file: 'aikidoselfscanner_linux_X86_64.zip'
      - name: unzip
        run: unzip aikidoselfscanner_linux_X86_64.zip
      - name: Run scan
        run: ./aikido-selfscanner --help
