on: workflow_dispatch

name: Scan
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          path: demo-app
      - name: Install Aikido selfscanner
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'skeymeulen/releasetetest'
          version: 'tags/v1'
          file: 'aikidoselfscanner_linux_X86_64.zip'
      - name: unzip
        run: unzip aikidoselfscanner_linux_X86_64.zip
      - name: test
        run: ls
      - name: Run scan
        run: ./aikido-local-scanner scan demo-app --apikey AIK_CI_vZOreWZuhM1s3fAEqejFWL2G84inBI8Mv5rLLFglicLnBDudHosTxJYVU4YruLQy --repositoryname MyRepo2 --branchname master
      - name: show temp folder
        if: success() || failure()
        run: ls /tmp
